### ISSUE TITLE
Rationale for prod server API gateway 

### ISSUE THREAD

**Issue by agahkarakuzu** [neurolibre/roboneuro#13]
@ltetrel I did my best to list the reasons why having an API gateway on the prod server can be of value after discussing with @emdupre. 

#### 1.1 Serving books 

**Generic:** For quite some time I was under the impression that the final book artifacts were going to be served through GitHub pages from a centralized repository and persist there. We were aware that this solution was suboptimal because the repo would get larger and larger over time and we would not have the all bundle of resources in one place that (physically) belongs to NeuroLibre. 

Feasibility checkbox: 

- [x] Serve static html from prod server 

#### 1.2 Cutting versions & Crossref 

**Specific:** Upon acceptance, we'll need to cut version for all the components of the submission using Zenodo API. We cannot do this on Heroku workers (highly limited memory) and from what @ltetrel said regarding file transfers, this would be heavy on the test server as well. 

The PDF of the submission lives on GitHub, although heroku workers would pull off crossref for a single PDF, to mint and collect DOIs (metadata) for other artifacts we need something more powerful.

Feasibility checkbox: 

- [x] API functionality to use Zenodo API for NeuroLibre artifacts

#### 1.3 Moving review workload to prod  server 

This way: 

* We have the artifacts already available on the prod 
* Advantage for data management given that that's where we have the storage 
* We can expect higher performance and have a feeling of how the final product will behave when published

Feasibility checkbox: 

- [x] API functionality similar to that on the test server for Binder & Book build

#### 1.4 Providing the version-cut repo for BinderHub

Following a complete build, I thought that BinderHub would use repository information (user/repo+commit) to find the right Docker image to spawn the right user instance, but not to consume what exists on the repo for that specific (user/repo+commit, assume that there are no changes, which will be the case upon publication). Is this correct? 

In any case, to build a Docker image on prod server, we need that repo to live under neurolibre organization for the time being. Questions regarding this: 

* Is there a way to grant build access to a repo on the fly? 
* Is there a more customized way for BinderHub to consume repository files from prod server's filesystem? 
 
### Appreciation 

I am aware that @ltetrel is dealing with a lot of backend components on 2 different cloud infrastructures. We spent months together getting ourselves familiar with all those things under the hood, and I know at first hand that these things are not necessarily a piece of cake. I just wanted to acknowledge this not to give you the impression that we are unreasonably requesting a lot of things from you without knowing what it takes :) 

### Validation 

I hope that it was clear. I would like to wait for sanity check by @emdupre before we proceed to discussion.

**Comment by emdupre** [comment]
Can we consider this resolved since the API has been added to the production server, or should we keep it open until the production API has been integrated into the workflow ?

**Comment by agahkarakuzu** [comment]
+1 for closing this and open other issues for the development ✌️
