### ISSUE TITLE
compilation failing

### ISSUE THREAD

**Issue by pbellec** [neurolibre/roboneuro#16]
I've used the neurolibre template to prepare a new submission. 
The repo is here:
https://github.com/pbellec/editorial_parcellation
The jupyter book is in `content`.

I have tested the submission with the roboneuro preview.
The pdf builds fine, but the notebooks crash.
First time the error message was `{}`. 
Second time it was something like `no notebook or paper found` then it switched to `{}` again (?). 

The jupyter book does not feature notebooks indeed, just myst files, but it compiles with jupyter book without issues.

**Comment by pbellec** [comment]
in my latest tests roboneuro seems to work reliably. Should we close this issue?

**Comment by emdupre** [comment]
+1 from me ! Then we can open dedicated issues on the API repo re : `Retry-After` and a new issue here re logging to-dos ☑️
