### ISSUE TITLE
Finalize acceptance workflow

### ISSUE THREAD

**Issue by emdupre** [neurolibre/roboneuro#19]
Moving conversation from https://github.com/neurolibre/neurolibre-reviews/issues/4

We have previously sketched (see #13 ) but not yet implemented the workflow on acceptance.

@agahkarakuzu @ltetrel can you update on your current understanding of that workflow ? I'm not sure that I'm aware of the latest discussions, here.

cc @pbellec

**Comment by agahkarakuzu** [comment]
I am only missing whether we have successfully served binder instance from a repository cloned to the server side, not from GitHub. 

After finalizing this, we can have prod API receive requests for zenodo depositions. @emdupre should we have a roboneuro Zenodo account for that?

**Comment by ltetrel** [comment]
> I am only missing whether we have successfully served binder instance from a repository cloned to the server side, not from GitHub.

No, we rely on Github.
Indeed it is possible for `repo2docker` on its own to create a docker image from a local repository. In the case of repo2docker within binderhub it **can be** more complicated.
I will confirm (maybe tomorrow) if such mechanism exists, I still need to finish some works on backend. It could be as simple as changing the binder request url to a local path.
Also can I have some background on why we want to have local repositories (for the fork i.e. production submission), instead of relying on github (making changes and push on github) ?

**Comment by emdupre** [comment]
Based on previous point from @pbellec in #10 :

> **Re where the artefacts live after acceptance:** The real artefacts (pdf | html | data | environment) need to live on the production server - that's where they are served to users. These artefacts are very precious as it may be challenging or even impossible to rebuild. Although this is not set up at the moment, we can add on offsite tape backup with compute canada easily.

I understood that we would like everything included in the submission to live on the production server at acceptance, including the supporting notebooks. The logic of triggering the Zenodo API also assumes this -- otherwise, we'd need a completely different mechanism to DOI the code if it is not also hosted on the production server.

Theoretically this should make the docker builds (marginally) faster for the end user as well, since they will rely on local resources rather than first retrieving the resources in the build process !

**Comment by ltetrel** [comment]
re-artifacts on server. Yes definitively we need to have them live on our backend and push to zenodo, and this is what we actually discussed with Agah last time, this include: data, docker images, book artifacts.
To be able to reproduce the environment, there is no need to store locally the git repository, it already exists in the docker image! If we absolutely need the **raw** original code, we can either extract it from the docker image, or pull from github after docker was built.

re-faster build, not true. In practice what would happen is that you would still need to (manually trigger through API) pull from github to backend storage, with a separate workflow, manage these local repository ourself and then asking binderhub to build from local. This will actually take more time, than just binderhub pulling from github to the build pod, and building directly the docker image (everything done locally of course). And I am not still even sure if that is possible in binderhub, need to test a local build.

I think at this stage if we want to have a working submission workflow, we would like to reduce the complexity of it. I don't want to over-engineer the workflow if not necessary. But let discuss that during our meeting if needed.

**Comment by ltetrel** [comment]
For now I pulled a repository into `/home/ubuntu/nha2020-nilearn`.
I tried with: `file:///home/ubuntu/nha2020-nilearn` and selecting "Git repository" but that was not working. Will see if I can find some documentation

**Comment by ltetrel** [comment]
Definitively @emdupre if you have some feedback from Chris on that, I would be happy to hear it. For now I posted on their gitter and will see if they answer.

**Comment by agahkarakuzu** [comment]
![image](https://user-images.githubusercontent.com/9632322/139922884-6344804f-a777-455c-aaa7-7148b5a3af75.png)

Day by day roboneuro is becoming a better researcher, now has a zenodo account. 

There are two main decisions we made today:

###  Complete the workflow by adding "on acceptance" actions

*  Sync the book `test` --> `prod` that is generated by the latest `author repo commit`      
     * Roboneuro will send the request to `prod`  
* Fork `author repo` into a separate `roboneuro` [organization](https://github.com/organizations/roboneurotest) and ensure that the `_config` points to `prod` (push a commit).
      * Roboneuro will perform through Heroku
* `Clone` either user repo or the fork on prod 
> @emdupre which one do you think we should archive,  given that the fork would be a commit ahead of user's repo. 
      * Roboneuro will request prod 
* Trigger a BinderHub build on `prod` 
      * Roboneuro will send the request to `prod` 
* After the build, we'll have a lookup table that has for a submission:
      * 1. Where is the data is on prod
      * 2. What is the Docker image ID (ideally we also have a tar)
      * 3. Where is the _book artifact_ on prod
      * 4. Where is the repository on prod 
             * Roboneuro will receive this information after a BinderHub build  
     * Deposit  1,2,3,4 on Zenodo (separately so that we have a DOI for each one of them, right @emdupre ?) 
             * Roboneuro will request `prod` to do the depositing 
             * Roboneuro will collect all the DOIs but that of PDF
     * PDF lives elsewhere, and roboneuro has enough power to deposit a PDF, it will take information from the previous step, add them into the pdf and
          * Deposit to Zenodo till we have the better option. 

An open question is about book artifacts having proper links (to the prod BinderHub instance):

* We update the link after syncing from `test` --> `prod` 
* We have test server build a book by enforcing `_config` to point to `prod`, then sync it. 

Which option do you think we follow? I am sure that we'll have few more iterations till we iron out the kinks given that it is in text now :)

**Comment by ltetrel** [comment]
> Sync the book `test` --> `prod` that is generated by the latest `author repo commit`
> 
>     * Roboneuro will send the request to `prod`

This can happen at the end if we do:
1. Environment + book building from user repo (with binder.conp.cloud, should be injected in config if user forget?)
2. After acceptance, fork user repo to our organization
3. update config to point to binder-mcgill.conp.cloud
4. Environment + book building from fork, tester can click on link (points to binder-mcgill.conp.cloud) to do a short test of prod, that way docker image is already built and ready for prod (updated docker image with new metadata pushed on registry by test, can be pulled on prod)! Books artifacts generated with the good link.

>     * * 4. Where is the repository on prod

So you still need the repo separately, even it already exists in the docker image ? I am not familiar with zenodo so I don't know it things needs to be transparent, of if things exists in the data that is enough ? I recall @emdupre talking about author information.

>     * We update the link after syncing from `test` --> `prod`

What link are you talking about here ? There is just one link that needs to be changed, from test to prod (in config if we rebuild, in html if we hard replace).

**Comment by emdupre** [comment]
> Fork author repo into a separate roboneuro organization and ensure that the _config points to prod (push a commit).
> @emdupre which one do you think we should archive, given that the fork would be a commit ahead of user's repo.

I don't think we want to push a commit. We just want to re-trigger a build, duplicating the correct YAML keys for eg force-re-execute and the binder link. We can pass the config file directly in the build command. So hopefully that resolves the question of which to archive :smile_cat: 

> We have test server build a book by enforcing _config to point to prod, then sync it.

Based on our discussion of updating the config, I was under the impression that we were moving forward with this option !

> So you still need the repo separately, even it already exists in the docker image ?
> Deposit 1,2,3,4 on Zenodo (separately so that we have a DOI for each one of them, right @emdupre ?)

Yes,  I think we want each of these separately such that in the PDF we can do something like `Data archive: XXX`, `Code archive: XXX`, `Book archive: XXX`, `Environment Archive: XXX`. If everyone agrees with this goal, then we will in fact need the repo separately from the docker image !
One clarification, though: The data archive may or not be populated depending on whether the user enables `repo2data` -- is that correct ?

**Comment by pbellec** [comment]
> > Fork author repo into a separate roboneuro organization and ensure that the _config points to prod (push a commit).
> > @emdupre which one do you think we should archive, given that the fork would be a commit ahead of user's repo.
> 
> I don't think we want to push a commit. We just want to re-trigger a build, duplicating the correct YAML keys for eg force-re-execute and the binder link. We can pass the config file directly in the build command. So hopefully that resolves the question of which to archive smile_cat

Agreed with that. We discussed both options on the call, but I think what Elizabeth suggests is the cleanest / easiest to maintain. 

> 
> > We have test server build a book by enforcing _config to point to prod, then sync it.
> 
> Based on our discussion of updating the config, I was under the impression that we were moving forward with this option !
> 

Yes, that's also my undestanding.

> > So you still need the repo separately, even it already exists in the docker image ?
> > Deposit 1,2,3,4 on Zenodo (separately so that we have a DOI for each one of them, right @emdupre ?)
> 
> Yes, I think we want each of these separately such that in the PDF we can do something like `Data archive: XXX`, `Code archive: XXX`, `Book archive: XXX`, `Environment Archive: XXX`. If everyone agrees with this goal, then we will in fact need the repo separately from the docker image ! One clarification, though: The data archive may or not be populated depending on whether the user enables `repo2data` -- is that correct ?

I agree with the goal, mostly. I definitely like the idea of archiving everything, so in principle everything could be reproduced from the archives. But for the data, I would tend not to archive. As you mention Elizabeth, it is dependent on the use of repo2data, so the reproducibility will only be partial. It is also duplicating public resources - the data needs to be open in the first place to be pulled by repo2data. We may allow fairly big datasets in the future which may not fit on zenodo. Overall, it feels a little bit like the conversation we had about reproducing builds: data should be pulled from a legitimate repository, with proper versioning. So it should be reproducible without a data archive, and if it is not the problem would not be with neurolibre. What we archive is the reproducible analysis that comes with the data. Sorry for the long post. Please let me know what you think.

**Comment by pbellec** [comment]
To follow up on my previous post re data deposition: one solution would be to add a field DOI in repo2data, and make that field mandatory for neurolibre submissions. This way we would not force a double deposition. And we would simply refuse to work with data pulled from a source which does not deal cleanly with DOIs. This may be a bit limiting, but it's the cleaner solution I can think of.
