### ISSUE TITLE
deposit crossref xml

### ISSUE THREAD

**Issue by pbellec** [neurolibre/roboneuro#20]
I have started looking into crossref.

One of the key task will be to upload meta-data for each preprint, in the form of an xml.
This is described here: https://www.crossref.org/documentation/member-setup/direct-deposit-xml/

I assume that, because JOSS also uses crossref, there is already code to take care of that which would simply need to be adapted for our use case.

Can you please confirm @emdupre ? @agahkarakuzu ?

**Comment by emdupre** [comment]
Confirmed !

**Comment by pbellec** [comment]
whoa, that was less than a minute turn around. Thanks @emdupre !
